### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by maxime1992** [inspect-js/is-equal#64]
Hi, thanks for the library!

It'd be really nice to have TS support with maybe just a d.ts file

Otherwise when using that library within a ts project with the option no implicit any we get an error:

```
Could not find a declaration file for module 'is-equal'. './node_modules/is-equal/index.js' implicitly has an 'any' type.
      Try `npm install @types/is-equal` if it exists or add a new declaration (.d.ts) file containing `declare module 'is-equal';`
```

**Comment by ljharb** [comment]
You’re welcome to submit a PR to DefinitelyTyped, but unless there’s a way for me to only author JavaScript, and also fail CI if the d.ts file doesn’t match the implementation, I’m not interested in maintaining any typescript.
