### ISSUE TITLE
Syntax error with which-collection dependency in 1.6.1

### ISSUE THREAD

**Issue by mccalluc** [inspect-js/is-equal#65]
I'm not sure if I'm diagnosing this correctly, but `is-equal@1.6.1` adds a dependency on `which-collection`, which causes a syntax problem for me when I try to run tests under nwb:

```
 ERROR  in ./node_modules/is-weakmap/index.js 12:1
Module parse failed: 'return' outside of function (12:1)
You may need an appropriate loader to handle this file type.
| 		return false;
| 	};
> 	return;
| }
|
 @ ./node_modules/which-collection/index.js 5:16-37
 @ ./node_modules/is-equal/why.js
 @ ./node_modules/expect/lib/TestUtils.js
 @ ./node_modules/expect/lib/SpyUtils.js
 @ ./node_modules/expect/lib/index.js
```

The real fix might be at a lower level, in `which-collection`... or it might be at a higher level in `nwb`... but for me, a simple fix was to pin `is-equal` to 1.6.0. Perhaps remove that dependency from this package until that package is stable? I'm not sure.

**Comment by ljharb** [comment]
That's not a syntax error - most everything on npm (including is-equal and which-collection) are CJS modules, in which top level return is quite valid.

What is nwb and why is it not providing a proper CJS wrapper around node modules?

**Comment by mccalluc** [comment]
https://github.com/insin/nwb : It's a project something like create-react-app. It sounds like the best course is to close this, and open an issue there. Thanks!

**Comment by ljharb** [comment]
Thanks, please link it here when you do, as I'm sure it will affect a number of my other packages.
